@url = http://localhost:8080/api/collectMe/category

GET {{url}} HTTP/1.1

###

GET {{url}}/1 HTTP/1.1

###

POST  {{url}} HTTP/1.1
Content-Type: application/json

{
    "shortName": "CIA",
    "longName": "Central Intelligence Agency",
    "locations": [],
    "agents": []
}

### [ ] PUT an alias

PUT {{url}}/2 HTTP/1.1
Content-Type: application/json

{
  "aliasId": 2,
  "agentId": 1,
  "name": "Test",
  "persona": "Something"
}

###

DELETE {{url}}/2 HTTP/1.1