@url = http://localhost:8080/api/category
@jwt = eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJjb2xsZWN0LW1lIiwic3ViIjoiTWljYWhhZWwiLCJ1c2VySWQiOjEsImF1dGhvcml0aWVzIjpbIkFETUlOIiwiVVNFUiJdLCJmaXJzdE5hbWUiOiJKYWNrc29uIiwibGFzdE5hbWUiOiJKTWljaCIsImVtYWlsIjoibWpAdGVzdGluZy5jb20iLCJleHAiOjE2ODA1NTgwNjV9.WWg1NA4j3ZhYQHwNfKG96J75EJFaIFN03CeqAXdjlT0
GET {{url}} HTTP/1.1

###

GET {{url}}/3 HTTP/1.1

### POST a Category ... be sure to replace the token in the Authorization header with a valid token

POST  {{url}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "categoryName": "Gnomes",
    "items": []

}

### [ ] PUT a Category

PUT {{url}}/5 HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
  "categoryId": 5,
  "categoryName": "Changed"
}

### Delete A Category

DELETE {{url}}/5 HTTP/1.1
Authorization: Bearer {{jwt}}

### Good User credentials

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "SWalk" ,
    "password": "go"
}

### Good Admin credentials

POST http://localhost:8080/authenticate HTTP/1.1
Content-Type: application/json

{
    "username": "JMich" ,
    "password": "go"
}